#!/bin/sh

# Unit test shell
# opt

NGX_VER=nginx-1.4.4
if [ `uname` == "AIX" ]
then
	ostype=aix
	CC=xlc	
else
	ostype=linux
	CC=gcc		
fi

gethomepath()
{
  currpath=`pwd`  
  HOME_PATH=`echo $currpath |sed "s/\/$NGX_VER/    /g" |  awk '{print $1}'`  
  echo "HOME_PATH:" $HOME_PATH  
  export HOME_PATH=$HOME_PATH
}

usage()
{
  echo "current path:" $currpath
  echo "os type:" $ostype
  echo "home path:" $HOME_PATH
  echo "current CC:" $CC  
	echo "usage: run \"unitname\" make "
	echo "usage: run \"unitname\"  "
}

gethomepath

if [ $# -eq 0 ] 
then
	usage
	exit 1
fi

if [ $# -eq 1 ] 
then
  
	UNAME=$1
	echo "run unit $UNAME"
	./bin/$UNAME
	exit 1
fi


if [ $# -eq 2 ] 
then
	UNAME=$1
	MAKE=$2
	cd ./$UNAME
	if [ "$ostype" == "aix" ]
	then
		$MAKE 
	else
		$MAKE -f Makefile.linux	
	fi
	cd ..
	exit 1
fi